name: Test

on:
  workflow_dispatch: {}
  pull_request:
    branches: [ master ]
  push:
    branches: [ mmaster ]

jobs:
  run-examples:
    strategy:
      fail-fast: false
      matrix:
        minor: [22, 24]
    runs-on: ubuntu-latest
    container:
      image: fedora:43
    steps:
      - uses: actions/checkout@v4

      - name: Install System build tools
        run: dnf install -y gcc cmake

      - name: Set up Conan
        uses: conan-io/setup-conan@v1

      - name: Select Wayland minor version
        run: sed -i -E 's/22/${{matrix.minor}}/' coanfile.txt

      - name: Conan install dependencies
        run: conan install . --build=missing
      
      - name: CMake setup
        run: cmake --preset conan-release -DCMAKE_VERBOSE_MAKEFILE=ON
      
      - name: CMake build
        run: cmake --build --preset conan-release
      
      - name: Run example
        run: source build/Release/generators/conanrun.sh && build/Release/wayland_egl_example

      